apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-hostpath-nginx-deployment
  namespace: openebs
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16.0
          resources:
            requests:
              cpu: "0.25"
              memory: 50Mi
            limits:
              cpu: "0.5"
              memory: 100Mi
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always
