apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-hostpath-nginx-deployment
  namespace: openebs
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        tier: super-worker 
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              cpu: "0.25"
              memory: 50Mi
            limits:
              cpu: "0.5"
              memory: 100Mi
          volumeMounts:
            - name: openebs-vol
              mountPath: /usr/share/nginx/html
      volumes:
        - name: openebs-vol
          persistentVolumeClaim:
            claimName: local-hostpath-pvc