apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-hostpath-pvc
  namespace: openebs
spec:
  storageClassName: local-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi